### ISSUE TITLE
(Suggestion) Remove all the chinese/japanese from the code

### ISSUE THREAD

**Issue by Husky110** [fumiama/Retrieval-based-Voice-Conversion-WebUI#20]
I'm posting this as a sort of "todo".  
It would be nice to get rid of all the asian characters within the code. I have no clue what they do (documentation I guess...) or what there actually for since I don't speak neither chinese or japanese. I totally see that it would be good to have some l18n in there, but open-source codebases should be strictly in english (just my oppionion!).  
I am actually facing the issue that I am new to python (beeing a PHP-Dev) and I can't make heads or tails out of this code... Is it possible to set all asiatic labels to translateable strings?

**Comment by 413x1nkp** [comment]
Yeah, we could just replace the chinese in-code with english and just make so all of the I18n strings use english strings from code as references to translating from what-to-what. This will be time consuming, but i genuinely believe it's worth it.
Will start working on this in the near future

**Comment by fumiama** [comment]
Maybe the best solution is to make a id file like what `strings.xml` does in Android, and refer to that var in every codes. This will prevent the long long sentences embedding inline.

**Comment by 413x1nkp** [comment]
> Maybe the best solution is to make a id file like what `strings.xml` does in Android, and refer to that var in every codes. This will prevent the long long sentences embedding inline.

True, this will be much easier to work with, also since it works practically just like the I18n, not a TON of changes are needed for that
The only downside might be the _slightly_ increased RAM usage during the entirety of `web.py`, but it's practically negligible

**Comment by 413x1nkp** [comment]
@Husky110 Please help with testing the PR implementing your suggestion. You can either apply with patch or clone my fork and checkout to `strings-xml` branch.

**Comment by Husky110** [comment]
@alexlnkp - Sorry, I am no Python-Dev. I'm doing PHP and since I've started my repo on different RVC-tools, I don't have the time. Right now I can only make general suggestions... :sweat_smile:

**Comment by 413x1nkp** [comment]
> @alexlnkp - Sorry, I am no Python-Dev. I'm doing PHP and since I've started my repo on different RVC-tools, I don't have the time. Right now I can only make general suggestions... 😅

It's alright! Though I would really appreciate if you checked out dev branch when You have time to see if localization works properly for You.

**Comment by Husky110** [comment]
@alexlnkp - Phew... Hardly, cause I build my images by shortly renting a server, building them there and delete the server. So building actually costs money (even tho not much). If you wanna try them yourself, got an NVIDIA-GPU and a bit knowledge of docker, just try it with this gist: https://gist.github.com/Husky110/3aac26555f30b2a2ed8c1678d2fe894b

**Comment by fumiama** [comment]
@alexlnkp Well, we can say that this issue has been solved without his check. So just let him do his stuffs 😂. I will mark this issue as complete.
