### ISSUE TITLE
"Invalid index" despite specifying the correct index file

### ISSUE THREAD

**Issue by TheTrustedComputer** [fumiama/Retrieval-based-Voice-Conversion-WebUI#32]
In the real-time GUI `gui_v1.py`, if one provides a model and an added index file to start the voice conversion, the error message ...

`Invalid index. You MUST use added_xxxx.index but not trained_xxxx.index!`

... appears. It's unclear why this happens, but it can cause some confusion for some users.

**Comment by fumiama** [comment]
Maybe it is because the index rate is set to zero.

**Comment by fumiama** [comment]
Solved by deleting this message. Now no message will be periodically shown on the realtime to disturb user.
