### ISSUE TITLE
Suggestion: Make English README the main README of the project

### ISSUE THREAD

**Issue by 413x1nkp** [fumiama/Retrieval-based-Voice-Conversion-WebUI#33]
Some people might be scared off by a base README being in Chinese, so using a more universally known language like English seems to be more suited for open-source projects, although this is just a suggestion.

Basically, I believe some people just come to the project, they see the README and then they're frightened to even work on/with it
Not everyone notices the `English` hyperlink in the README itself too, so a lot of users end up not even knowing english README exists (I was one of those people, lol)

**Comment by fumiama** [comment]
I agree, just a simple change, so you can create a pr.

**Comment by 413x1nkp** [comment]
> I agree, just a simple change, so you can create a pr.

Alrighty! I'll make the PR after #31 is resolved
The changes might clash onto each other otherwise

**Comment by 413x1nkp** [comment]
Since #31 is no longer clashing with documentation, I'll make a PR for this change right now.

**Comment by 413x1nkp** [comment]
Solved by the merge of #38
