### ISSUE TITLE
RVC Pre-trained Model Training CodeRVC Pre-trained Model Training Code

### ISSUE THREAD

**Issue by CHK-0000** [fumiama/Retrieval-based-Voice-Conversion-WebUI#64]
hello. I would like to train the RVC pre-trained model with my own Korean song data and try it out, could you please provide the code for training the pre-trained model? Thank you.

**Comment by fumiama** [comment]
There is no different from the normal training code.

**Comment by ksl103177** [comment]
> 일반학습코드와 별반 차이가 없습니다.

**Comment by fumiama** [comment]
After the training, remove the `epoch xx` info in the pth info field to make it possoble to train from 0 epoch.

**Comment by CHK-0000** [comment]
I'd be interested in testing it out though, so if you can, could you provide the code?

**Comment by fumiama** [comment]
What code? If you mean the info editing, it's already in the webui.

**Comment by CHK-0000** [comment]
Is there code that can generate a pre-trained model rather than code that learns by fine-tuning a pre-trained model?

**Comment by fumiama** [comment]
Just delete the pre-trained model (f0D/Gxxk.pth) in the training textbox, the program will init a model from zero.

**Comment by CHK-0000** [comment]
I'm using RVC as a CLI environment right now, so if I don't specify a pre-trained model, it will initialize the model from zero and train?

**Comment by fumiama** [comment]
Not so sure for CLI. You can simply delete all pretrained models to force it init from zero.

**Comment by CHK-0000** [comment]
So in WEBUI, the path of the pre-trained model can be initialized to 0 if not specified?

**Comment by fumiama** [comment]
Sure.

**Comment by CHK-0000** [comment]
Thank you for your quick response, it was helpful...!
