### ISSUE TITLE
Automated build for windows zip release using github action

### ISSUE THREAD

**Issue by hgftrdw45ud67is8o89** [fumiama/Retrieval-based-Voice-Conversion-WebUI#68]
**Is your feature request related to a problem? Please describe.**
It would be awesome to have a github action script to allow users to clone and auto build the whole thing and allow you to release periodically like the ori repo.

**Describe the solution you'd like**
make a github action script in the repo,that can be triggered by user to run.

**Describe alternatives you've considered**
no idea.

**Comment by fumiama** [comment]
Well, it depends on the user's environment (ex. CUDA version, python version, etc.) so we cannot satisfy all they need. Some cards cannot run on the latest version of torch, while others must use the latest one. The pack in the original repo is really ugly (Windows only, different cards have different packs) and the zip file is too large to put on the GitHub release so it is hard for me to imply it.

**Comment by hgftrdw45ud67is8o89** [comment]
hmmm,i see.true. I checked and the ori repo uses huggingface to store.

Seems like my idea won't be perfectly possible. Maybe we can only built and pick only 1.
- include cuda/amd
- include base pretrained models

I personally would recommend include the cuda/amd if can.
Because properly setting up cuda/amd support is not really *xiao bai* friendly
But unzip in a specific place/folder is more *xiao bai* okok level.

For the torch problem personally in nvidia i never had problem. Range from (1050ti to 4070),all use the same rvc ori repo zip.
AMD probably have the torch version problem.

For the torch problem I think if really have problem then we can add a wiki.
hope user read and find how to use the venv and run>pip install torch=xxxx

**Comment by fumiama** [comment]
Well, at first, 小白 cannot reach GitHub page 😂. Since this repo is mainly faced to the developers, I think it is a little bit useless. If 小白 want to use an one-click pack, just go to the original RVC repo or 花儿不哭's bilibili account.
