### ISSUE TITLE
FCPE for training models

### ISSUE THREAD

**Issue by Player124413** [fumiama/Retrieval-based-Voice-Conversion-WebUI#78]
Hello, can you please add fcpe for training models? Hold the repository https://github.com/IAHispano/Applio/tree/exp-fcpe

**Comment by fumiama** [comment]
Of course. Now training is still under refactoring.

**Comment by TheTrustedComputer** [comment]
Don't quote me, but I've heard FCPE has trouble with silence. I don't have the details as to why, but it's something to think about. Perhaps later versions may resolve it.

**Comment by fumiama** [comment]
Added.
