### ISSUE TITLE
Errors appear in the Gradio UI but not in the console

### ISSUE THREAD

**Issue by robobun7** [fumiama/Retrieval-based-Voice-Conversion-WebUI#83]
**Describe the bug**
When I try to load weights or perform inference, I get errors appearing in the UI but no corresponding information in the console.

The python process still shows activity in Task Manager, as if the script is running in the background, but nothing appears on the page.

**To Reproduce**
I simply tried loading the weights and running an inference, and I received these errors.

**Expected behavior**
I expected to be able to use the program.

**Screenshots**
![image](https://github.com/user-attachments/assets/85651860-3443-407a-92f2-ac66b20efa55)
![image](https://github.com/user-attachments/assets/c2c97809-2ccd-4f69-8b47-0d61516bb4e4)
![image](https://github.com/user-attachments/assets/0e2e41e6-a3ee-432a-8494-f9e5eedf7eda)

**Desktop (please complete the following information):**
 - OS and version: Windows 10 22H2
 - Python version: 3.10.14
 - Commit/Tag with the issue: 412a995

**Additional context**
If there's any debug mode that I could enable to get more information in the console, that would be great.

**Comment by fumiama** [comment]
Quite strange 😂. I noticed that you are using conda. Maybe you can try `venv` and see what will happen.

**Comment by robobun7** [comment]
It works fine with venv instead of conda.

**Comment by fumiama** [comment]
Now you can use it normally. We still want to figure out why conda didn't work but it may take a long time.

**Comment by robobun7** [comment]
You should probably remove the line in the readme that recommends conda until the bug is fixed.

**Comment by fumiama** [comment]
> You should probably remove the line in the readme that recommends conda until the bug is fixed.

No problem.
