### ISSUE TITLE
Training restarts at checkpoint instead of continuing

### ISSUE THREAD

**Issue by TheTrustedComputer** [fumiama/Retrieval-based-Voice-Conversion-WebUI#85]
**Describe the bug**
This seems to be an unintentional regression. If one stops training mid-session and resumes, it starts from the beginning instead of continuing with the saved D and G checkpoints. The initial output shows these files aren't even loaded when they exist in the file system.

**To Reproduce**
Create any RVC model in the training tab, stop after the first checkpoint, and repeat, using the same parameters.

**Expected behavior**
Training should continue from the previously saved checkpoint, as RVC always has.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS and version: Arch Linux
 - Python version: 3.10.13
 - Commit/Tag with the issue: main

**Additional context**
This is likely due to the commit 277eadca9ad25b9092aaccb2144b05fae0e190af, which renamed checkpoint files from "2333333" to "latest". Resumption from the latest checkpoint worked in an older commit, but it's broken now.

**Comment by fumiama** [comment]
Maybe a digital epoch name is needed to resume in current code. We should modify the code and let the program check the name `latest` first.
