### ISSUE TITLE
[Feature]: add text-to-singing 🎤🎵

### ISSUE THREAD

**Issue by funmolde** [fumiama/Retrieval-based-Voice-Conversion-WebUI#89]
Hello 😀,

I'd like to suggest adding a text-to-singing voice synthesis feature.

https://github.com/topics/singing-voice-synthesis

Thank you -_-

**Comment by fumiama** [comment]
This program is a Voice Changer, which means that it is neither a TTS nor a song synthesizer. It only aims on changing EXISTING voice.
